---
services:
  spis:
    image: "ghcr.io/gbbirkisson/spis:latest"
    ports:
      - "8080:8080"
    environment:
      SPIS_MEDIA_DIR: "/var/lib/spis/media"
      SPIS_DATA_DIR: "/var/lib/spis/data"
      SPIS_PROCESSING_SCHEDULE: "0 0 2 * * *"
      SPIS_PROCESSING_RUN_ON_START: "false"
      SPIS_FEATURE_FAVORITE: "true"
      SPIS_FEATURE_ARCHIVE: "true"
      RUST_LOG: "error,spis=info"
    volumes:
      # This assumes you want to keep the SPIS data in a
      # docker volume and not in some directory
      - "data:/var/lib/spis/data"
      - "/tmp/media:/var/lib/spis/media"
volumes:
  data:
