---
services:
  spis:
    image: "ghcr.io/gbbirkisson/spis:latest"
    ports:
      - "8080:8080"
    environment:
      SPIS_PROCESSING_SCHEDULE: "0 0 2 * * *"
      SPIS_PROCESSING_RUN_ON_START: "false"
      SPIS_FEATURE_FAVORITE: "true"
      SPIS_FEATURE_ARCHIVE: "true"
      SPIS_FEATURE_FOLLOW_SYMLINKS: "true"
      RUST_LOG: "error,spis=info"
    volumes:
      - "/tmp/spis_data:/var/lib/spis/data"
      - "/tmp/spis_media:/var/lib/spis/media"
