[tasks."dev:nginx"]
run = """
cat << EOF > /tmp/nginx.conf
daemon off;

error_log /dev/stdout info;
pid       /tmp/nginx.pid;

events {
    # No special events for this simple setup
}

http {
EOF

cat docker/nginx.conf | envsubst >> /tmp/nginx.conf

cat << EOF >> /tmp/nginx.conf
}
EOF

sed -i 's/Upgrade ;/Upgrade $http_upgrade;/g' /tmp/nginx.conf

cat /tmp/nginx.conf
nginx -c /tmp/nginx.conf > /dev/null
"""

[tasks."dev:spis"]
run = "make dev-spis"

[tasks."dev"]
depends = ["dev:nginx", "dev:spis"]
