---
services:
  spis:
    image: "ghcr.io/gbbirkisson/spis:{{ spis_version }}"
    ports:
      - "8080:8080"
    environment:
      SPIS_PROCESSING_SCHEDULE: "{{ config.processing_schedule }}"
      SPIS_PROCESSING_RUN_ON_START: "{{ config.processing_run_on_start }}"
      SPIS_FEATURE_FAVORITE: "{{ config.feature_favorite }}"
      SPIS_FEATURE_ARCHIVE: "{{ config.feature_archive }}"
      SPIS_FEATURE_FOLLOW_SYMLINKS: "{{ config.feature_follow_symlinks }}"
      RUST_LOG: "{{ spis_log }}"
    volumes:
      - "{{ config.data_dir.to_str().unwrap() }}:/var/lib/spis/data"
      - "{{ config.media_dir.to_str().unwrap() }}:/var/lib/spis/media"
