---
name: rustup
description: "Install Rust toolchain"

runs:
  using: "composite"
  steps:
    - name: "Install rust toolchain"
      run: |
        # Copy bins from cache if present
        mkdir -p ~/.cargo/bin_cache ~/.cargo/bin
        touch ~/.cargo/bin_cache/empty

        echo asdf
        ls ~/.cargo/bin_cache
        echo asdf

        cp -f ~/.cargo/bin_cache/* ~/.cargo/bin

        # Install everything needed
        # make setup-toolchain

        # Move bins to bin_cache
        # cat rust-toolchain.toml | grep '# bin' | sed 's/sqlx-cli/sqlx/g' | xargs -n 4 sh -c 'cp -f ~/.cargo/bin/$2 ~/.cargo/bin_cache'
      shell: bash

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: toolchain
        cache-directories: ~/.cargo/bin_cache

    - name: "Set environment variables used by toolchain"
      run: |
        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=1 >> $GITHUB_ENV

        rustc --version --verbose
      shell: bash
