---
name: rustup
description: "Install Rust toolchain"

inputs:
  bin-cache:
    description: 'Where to keep cached bins'
    required: false
    default: /home/runner/.bin-cache

runs:
  using: "composite"
  steps:
    - name: Setup caching
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: toolchain
        cache-directories: ${{ inputs.bin-cache }}

    - name: "Set environment variables used by toolchain"
      run: |
        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=1 >> $GITHUB_ENV
      shell: bash

    - name: "Install rust toolchain"
      run: |
        # Make sure bin-cache dir exists with something in it
        mkdir -p ${{ inputs.bin-cache }}
        touch ${{ inputs.bin-cache }}/empty

        cp ${{ inputs.bin-cache }}/* /home/runner/.cargo/bin

        # Install everything needed
        make setup-toolchain

        # Move bins to bin_cache
        cat rust-toolchain.toml | grep '# bin' | sed 's/sqlx-cli/sqlx/g' | xargs -n 4 sh -c 'cp -f /home/runner/.cargo/bin/$2 ${{ inputs.bin-cache }}'

        rustc --version --verbose
      shell: bash
