---
name: toolchain
description: "Install toolchain"

inputs:
  cache-key:
    description: "Cache key for rust-cache"
    required: false
    default: "release"

runs:
  using: "composite"
  steps:
    - name: Setup rust caching
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.cache-key }}

    - name: "Set environment variables used by toolchain"
      shell: bash
      run: |
        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=1 >> $GITHUB_ENV

    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: |
          clippy
          rustfmt
        targets: |
          x86_64-unknown-linux-gnu,
          armv7-unknown-linux-gnueabihf,
          aarch64-unknown-linux-gnu

    - name: Install cross compilation dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        version: 1.0
        packages: gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

    - name: Install taplo
      uses: taiki-e/install-action@v2
      with:
        tool: taplo

    - name: Install sqlx-cli
      uses: taiki-e/cache-cargo-install-action@v3
      with:
        tool: sqlx-cli@0.8.6

    - name: Install cargo-tarpaulin
      uses: taiki-e/cache-cargo-install-action@v3
      with:
        tool: cargo-tarpaulin@0.35.0
