---
name: rustup
description: "Install Rust toolchain"

runs:
  using: "composite"
  steps:
    - name: "Install rust toolchain"
      run: |
        make setup-toolchain
      shell: bash

    - uses: Swatinem/rust-cache@v2

    - name: "Set environment variables used by toolchain"
      run: |
        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=1 >> $GITHUB_ENV

        rustc --version --verbose
      shell: bash
