---
name: rustup
description: "Install Rust toolchain"

runs:
  using: "composite"
  steps:
    - name: "Install rust toolchain"
      run: |
        ls ~/.cargo

        # Copy from backup folder if present
        mkdir -p ~/.cargo/bak ~/.cargo/bin
        touch ~/.cargo/bak/empty
        cp -f ~/.cargo/bak/* ~/.cargo/bin

        ls ~/.cargo/bin
        ls ~/.cargo/bak
        #make setup-toolchain

        # Backup binaries
        cat rust-toolchain.toml | grep '# bin' | sed 's/sqlx-cli/sqlx/g' | xargs -n 4 sh -c 'cp -f ~/.cargo/bin/$2 ~/.cargo/bak'
      shell: bash

    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: toolchain

    - name: "Set environment variables used by toolchain"
      run: |
        echo CARGO_TERM_COLOR=always >> $GITHUB_ENV
        echo CARGO_INCREMENTAL=0 >> $GITHUB_ENV
        echo RUST_BACKTRACE=1 >> $GITHUB_ENV

        rustc --version --verbose
      shell: bash
